### ISSUE TITLE
Realign LED, buttons and light sensor with touch screen

### ISSUE THREAD

**Issue by DSpeichert** [smeisner/smart-thermostat#53]
For a usable & aesthetic case design:

* raise RGB LED to touchscreen level
* raise RESET/BOOT buttons to almost touchscreen level
* lower/move/hide C6 capacitor (it protrudes too close to screen height)
* Rotate 90 degrees the UART port so it can be connected from the bottom/side

**Comment by smeisner** [comment]
> For a usable & aesthetic case design:
> 
> * raise RGB LED to touchscreen level

The intent of this device is not to have any buttons or indicators that aren't required/useful, as mentioned in the README.md.

> * raise RESET/BOOT buttons to almost touchscreen level

The intent of this device is not to have any buttons or indicators that aren't required/useful, as mentioned in the README.md.

> * lower/move/hide C6 capacitor (it protrudes too close to screen height)

This is a side effect of the prototype to create the smallest amount of AC ripple as possible. This cap will not be part of the final designed, as we discussed in email.

> * Rotate 90 degrees the UART port so it can be connected from the bottom/side

Already done in the latest version of the PCB.
